name: flask
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libmpdec=4.0.0=h827c3e9_0
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py313haa95532_1
  - pip=25.3=pyhc872135_0
  - python=3.13.11=h260b955_100_cp313
  - python_abi=3.13=3_cp313
  - setuptools=80.10.1=py313haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - blinker==1.9.0
      - click==8.3.1
      - colorama==0.4.6
      - flask==3.1.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - werkzeug==3.1.5
prefix: C:\Users\USER\.anaconda\envs\flask
